### ISSUE TITLE
hotfuzz breaks vertico-directory, marginalia-mode, all-the-icons

### ISSUE THREAD

**Issue by sjrmanning** [axelf4/fizz.el#10]
hotfuzz is super-quick and sorting looks great, so hoping I can get this working! I haven't worked out why yet, but when I set `completion-styles` to `'(hotfuzz)`, it breaks how vertico-directory works, removes all-the-icons icons, and removes margnalia's info from find-file. Interestingly marginalia still works `M-x` and hotfuzz, just not `find-file`.

Below is a minimal init.el that you can put in a directory, e.g. /tmp/emacs-init, and run emacs with e.g. `emacs --init-directory /tmp/emacs-init` to observe this:

```emacs-lisp
;; Bootstrap straight.
(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 6))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/radian-software/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

(setq straight-use-package-by-default t)

(use-package vertico
  :straight (vertico :files (:defaults "extensions/*"))
  :hook after-init
  :bind (:map vertico-map
              ("RET" . vertico-directory-enter)
              ("DEL" . vertico-directory-delete-char)
              ("M-DEL" . vertico-directory-delete-word)))

(use-package marginalia
  :hook after-init
  :custom
  (marginalia-max-relative-age 0)
  (marginalia-align 'left))

(use-package all-the-icons
  :if (display-graphic-p))

(use-package all-the-icons-completion
  :if (display-graphic-p)
  :after marginalia
  :hook ((after-init)
         (marginalia-mode . all-the-icons-completion-marginalia-setup)))

(use-package hotfuzz
  :hook (vertico-mode . hotfuzz-vertico-mode)
  :custom (completion-styles '(hotfuzz)))
```

If you comment out the hotfuzz use-package and test `find-file` everything works as usual. Any ideas?

(cc @minad — as the owner of some of the affected packages I wonder if you might see an obvious issue we can fix? :)

**Comment by axelf4** [comment]
Thanks for reporting this issue! Should be fixed now, though I only tested with Marginalia, so please check whether any problems with the other packages remain.

**Comment by sjrmanning** [comment]
Fixed ✅ Thank you so much!
