### ISSUE TITLE
Fuzzy matching for `company-mode' 

### ISSUE THREAD

**Issue by hongyi-zhao** [axelf4/fizz.el#11]
Does this package work with [`company-mode`](https://github.com/company-mode/company-mode)?

Regards,
Zhao

**Comment by axelf4** [comment]
With Company the matching is done by the specific completion backends. Some, e.g. the `company-capf` backend, will do matching according to the value of `completion-styles` to which hotfuzz can be added. With other backends you may be out of luck.
