### ISSUE TITLE
Add to compiling instruction for non-standard builds to README (e.g. macOS - emacsformacos)

### ISSUE THREAD

**Issue by ed9w2in6** [axelf4/fizz.el#15]
Hi, I use a build from [emacsformacos](https://emacsformacos.com/builds) and the Emacs installation structure is non-standard for its build.

FWIW,  to compile **hotfuzz** on such non-standard setup one will need to set the environment variable
`EMACS_ROOT` to the root directory of Emacs (i.e. the directory contains the `include/`,  `lisp/`, `site-lisp/`, etc.)

For **emacsformacos**, one should set to it to `EMACS_ROOT` to `'/Applications/Emacs.app/Contents/Resources/'`.

Maybe these information should be added to README.

**Comment by ed9w2in6** [comment]
An unrelated note to this issue: 
I had also adopted commits from #13 , which allows [consult](https://github.com/minad/consult) to use **hotfuzz** in more situations.  I think it can be merged.

**Comment by jwr** [comment]
As a data point, I built the provided module on MacOS using the default instructions:
```
mkdir build
cd build
cmake -DCMAKE_C_FLAGS='-O3 -march=native' .. \
	&& cmake --build .
```
and it worked right away. I'm using emacs-mac from the homebrew `railwaycat/emacsmacport` tap.

I also had to use the defadvice workaround to make hotfuzz work with consult.
