### ISSUE TITLE
hotfuzz fails on (potentially) long lines

### ISSUE THREAD

**Issue by jojojames** [axelf4/fizz.el#4]
I've written a function like this:
```
(defun zsh-history ()
  "Copy a command from ~/.zsh_history."
  (interactive)
  ;; https://emacs.stackexchange.com/questions/8115/make-completing-read-respect-sorting-order-of-a-collection
  (let* ((my-presorted-completion-table-fn
          (defun my-presorted-completion-table (completions)
            (lambda (string pred action)
              (if (eq action 'metadata)
                  `(metadata (display-sort-function . ,#'identity))
                (complete-with-action action completions string pred)))))
         (command
          (with-temp-buffer
            (insert-file-contents-literally "~/.zsh_history")
            (let ((history-list
                   (split-string (buffer-string)
                                 "^:[[:space:]][[:digit:]]+:0;"
                                 t
                                 "\n")))
              (completing-read
               "Command: "
               (funcall my-presorted-completion-table-fn
                        (reverse history-list)))))))
    (when command
      (message (format "Copying %s to clipboard." command))
      (kill-new command))))
```

My .zsh_history has quite a few lines of upwards of 20,000 characters, etc. With the hotfuzz completion-style, this will fail and crash/stall the entire completion.

I integrated your scoring algorithm into its own scoring function here: https://github.com/jojojames/fussy#hotfuzz to see if I can get past this issue.

Commit: https://github.com/jojojames/fussy/commit/59d75816e111bfc4be8342cee59df0035a181a95

I have a defcustom/variable here https://github.com/jojojames/fussy/blob/59d75816e111bfc4be8342cee59df0035a181a95/fussy.el#L78 to control the max length of a string to attempt to score. It's at 1000 by default (will probably change it to 500 soon) and even that fails. Once I change this variable's to something like 500, hotfuzz is able to work with my zsh-history completing-read function.

Integration here: https://github.com/jojojames/fussy/blob/59d75816e111bfc4be8342cee59df0035a181a95/fussy.el#L732

I noticed hotfuzz doesn't yet have highlighting with vertico (looks like that's in progress here: https://github.com/axelf4/hotfuzz/pull/3). Highlighting+hotfuzz works in fussy leveraging the built-in highlighting code, though it may not be 100% perfect.

**Comment by axelf4** [comment]
Thanks for reporting the issue, it should be fixed now. The code reuses a vector of length 512 for the bonuses, but some length checks were missing. It may make sense to up this limit to 1024 in the future.
